/*
 * This source file was generated by the Gradle 'init' task
 */
package amnesicChat;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void hasGetGreeting() {
        bin classUnderTest = new bin();
        assertNotNull(classUnderTest.getGreeting(), "Application should have a greeting");
    }
}
