/*
 * This source file was generated by the Gradle 'init' task
 */
package amnesicChat;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertNotNull(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
