/*
 * This source file was generated by the Gradle 'init' task
 */
package amnesicChat;

public class bin {
	public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new bin().getGreeting());
    }
}
